# import json
# import os
# from groq import Groq
# from src.portfolioagent import PortfolioAgent

# client = Groq(api_key=os.getenv("GROQ_API_KEY"))
# agent = PortfolioAgent()


# def normalize_sql(sql: str) -> str:
#     return " ".join(sql.lower().strip().split())


# def extract_sql_from_history(response):
#     """
#     Extract SQL from tool calling history
#     """
#     history = response.automatic_function_calling_history

#     for item in history:
#         if item.role == "model":
#             for part in item.parts:
#                 if hasattr(part, "function_call") and part.function_call:
#                     args = part.function_call.args

#                     # adjust based on your tool
#                     if "query" in args:
#                         return args["query"]
#                     if "sql" in args:
#                         return args["sql"]

#     return None


# # ---------------- GROQ JUDGE ----------------
# def groq_sql_judge(gt_sql: str, gen_sql: str):
#     prompt = f"""
# You are an expert SQL evaluator.

# Compare the two SQL queries below:

# GROUND TRUTH SQL:
# {gt_sql}

# GENERATED SQL:
# {gen_sql}

# Rules:
# - Ignore formatting, whitespace, alias names
# - Focus on joins, filters, grouping, aggregation, limits
# - Decide if they are logically equivalent

# Return ONLY valid JSON:
# {{
#   "match": true or false,
#   "score": 0.0 to 1.0,
#   "reason": "short explanation"
# }}
# """

#     response = client.chat.completions.create(
#         model="llama-3.1-8b-instant",
#         messages=[
#             {"role": "system", "content": "You are a strict SQL evaluation system."},
#             {"role": "user", "content": prompt}
#         ],
#         temperature=0
#     )

#     try:
#         return json.loads(response.choices[0].message.content)
#     except:
#         return {
#             "match": False,
#             "score": 0.0,
#             "reason": "Failed to parse Groq response"
#         }


# # ---------------- MAIN EVAL ----------------
# def run_evaluation(file_path="ground_truth_dataset.json"):
#     with open(file_path, "r") as f:
#         data = json.load(f)

#     questions = data["questions"]

#     total = len(questions)
#     correct = 0

#     print("\n================ GROQ EVALUATION START ================\n")

#     for q in questions:
#         qid = q["id"]
#         question = q["question"]
#         qtype = q["type"]
#         gt = q["ground_truth"]

#         print(f"\n[Q{qid}] {question}")

#         response = agent.answer_question(question)

#         # ---------------- TEXT2SQL ----------------
#         if qtype == "text2sql":
#             gt_sql = gt["sql_query"]
#             gen_sql = extract_sql_from_history(response)

#             print("\nExpected SQL:", gt_sql)
#             print("Generated SQL:", gen_sql)

#             if not gen_sql:
#                 print("❌ No SQL generated by agent")
#                 continue

#             judge = groq_sql_judge(gt_sql, gen_sql)

#             is_correct = judge["match"]

#             print("\n--- GROQ JUDGE ---")
#             print("Match:", judge["match"])
#             print("Score:", judge["score"])
#             print("Reason:", judge["reason"])

#         elif qtype == "exposure_calculator":
#             expected_tool = gt["tool_name"]



#             history = response.automatic_function_calling_history
#             used_tool = None

#             for item in history:
#                 if item.role == "model":
#                     for part in item.parts:
#                         if hasattr(part, "function_call") and part.function_call:
#                             used_tool = part.function_call.name

#             is_correct = (used_tool == expected_tool)

#             print("Expected Tool:", expected_tool)
#             print("Used Tool:", used_tool)
#             print("Matched:", is_correct)

#         else:
#             is_correct = False

#         if is_correct:
#             correct += 1

#     # ---------------- FINAL REPORT ----------------
#     accuracy = (correct / total) * 100

#     print("\n================ FINAL RESULTS ================\n")
#     print(f"Total Questions: {total}")
#     print(f"Correct: {correct}")
#     print(f"Accuracy: {accuracy:.2f}%")
#     print("\n==============================================\n")


# # ---------------- RUN ----------------
# if __name__ == "__main__":
#     run_evaluation()

    
import json
import os
from groq import Groq
from src.portfolioagent import PortfolioAgent
agent = PortfolioAgent()

def extract_tool_results_text2sql(response):
    extracted = []
    current_tool = None

    for item in response.automatic_function_calling_history:

        # Capture tool used
        if item.role == "model":
            for part in item.parts:
                if hasattr(part, "function_call") and part.function_call:
                    current_tool = part.function_call.name

        # Capture tool response
        elif item.role == "user":
            for part in item.parts:

                if hasattr(part, "function_response") and part.function_response:
                    result_data = part.function_response.response.get("result", {})

                    extracted.append({
                        "tool_used": current_tool,
                        "query": result_data.get("sql"),
                        "result": result_data.get("result"),
                        "result_type": result_data.get("type"),
                    })

    return extracted

def extract_tool_results_exposure_calculator(response):
    extracted = []
    current_tool = None

    for item in response.automatic_function_calling_history:

        # Capture tool used
        if item.role == "model":
            for part in item.parts:
                if hasattr(part, "function_call") and part.function_call:
                    current_tool = part.function_call.name

        # Capture tool response
        elif item.role == "user":
            for part in item.parts:

                if hasattr(part, "function_response") and part.function_response:
                    result_data = part.function_response.response.get("result", {})

                    extracted.append({
                        "tool_used": current_tool,
                        "portfolio_name": result_data.get("portfolio"),
                        "sector_exposures": result_data.get("sector_exposures")
                    })

    return extracted

import os
import json
from dotenv import load_dotenv
from groq import Groq


def groq_sql_judge(query1, query2):
    """
    Uses Groq LLM as a judge to determine whether two SQL queries
    are semantically equivalent.

    Returns:
        bool -> True if equivalent, else False
    """

    # Load environment variables
    load_dotenv()

    api_key = os.getenv("GROQ_API_KEY")

    if not api_key:
        raise ValueError("GROQ_API_KEY not found in .env file")

    client = Groq(api_key=api_key)

    prompt = f"""
You are an expert SQL evaluator.

Your task is to determine whether TWO SQL queries are semantically equivalent.

Rules:
- Ignore formatting differences.
- Ignore alias naming differences.
- Ignore capitalization differences.
- Ignore column order ONLY if result semantics remain same.
- Focus on whether both queries return the SAME logical result.
- Return STRICT JSON only.

Output format:
{{
    "equivalent": true
}}

OR

{{
    "equivalent": false
}}

Query 1:
{query1}

Query 2:
{query2}
"""

    try:
        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            temperature=0,
            response_format={"type": "json_object"},
            messages=[
                {
                    "role": "system",
                    "content": "You are a strict SQL semantic equivalence judge."
                },
                {
                    "role": "user",
                    "content": prompt
                }
            ]
        )

        content = response.choices[0].message.content
        parsed = json.loads(content)

        return bool(parsed.get("equivalent", False))

    except Exception as e:
        print(f"[groq_sql_judge ERROR] {e}")
        return False
    
def run_evaluation(file_path="ground_truth_dataset.json"):
    with open(file_path, "r") as f:
        data = json.load(f)

    questions = data["questions"]

    total = len(questions)
    correct = 0

    for q in questions:
        import time

        time.sleep(60)
        qid = q["id"]
        question = q["question"]
        qtype = q["type"]
        gt = q["ground_truth"]

        
        print(f"\n[Q{qid}] {question}")

        response = agent.answer_question(question)
        
        if q['type']== 'text2sql':
            expected_sql = gt["sql_query"]
            expected_result_type = gt["expected_result_type"]
            

            generated_data = extract_tool_results_text2sql(response=response)
            query = generated_data[0]['query']
            tool_used = generated_data[0]['tool_used']
            result_type = generated_data[0]['result_type']

            if not query:
                print("❌ No SQL generated by agent")
                continue
            is_correct = groq_sql_judge(expected_sql, query)

            print("\n--- GROQ JUDGE ---")
            print("Match:", is_correct)



            
        
        elif qtype == "exposure_calculator":
            expected_tool = gt["tool_name"]
            
            generated_data = extract_tool_results_exposure_calculator(response)
            tool_used = generated_data[0]['tool_used']

            if expected_tool == tool_used:
                is_correct = True

            else:
                is_correct = False
            
            print("Match:", is_correct)

        if is_correct:
            correct += 1 
            

    accuracy = (correct / total) * 100


    print("\n================ FINAL RESULTS ================\n")
    print(f"Total Questions: {total}")
    print(f"Correct: {correct}")
    print(f"Accuracy: {accuracy:.2f}%")
    print("\n==============================================\n")


if __name__ == "__main__":
    run_evaluation()